### ISSUE TITLE
Lights Not Working, Missing Method to Get All Lights

### ISSUE THREAD

**Issue by andrewlalis** [SteveTheEngineer/Immersive-Vehicles-Remote-Control#2]
The `setLight(name, state)` method does not appear to have any effect when it is called on a car using the correct `"HEADLIGHT"` name.

Also somewhat related is the fact that it is quite difficult at the moment to obtain the list of lights on a vehicle since right now I'm just iterating over the names found via the `getConstants` method which imposes quite a bit of unnecessary overhead for the OC computer. It would be nice to have a `getLights` or `getAvailableLights` method.

**Comment by SteveTheEngineer** [comment]
Thank you for your time, I'll look into it soon

**Comment by SteveTheEngineer** [comment]
I've tried it myself, and it was working fine. I'll probably add `getAvailableLights` in the future. Or you could attempt implementing it yourself, if you wish. Just make sure the MTS content pack you're using supports the latest version of MTS, and as the creator of MTS does breaking changes all the time, make sure to use the corresponding IVRC version to your MTS version. You can find the MTS version in the file name on curseforge.

**Comment by SteveTheEngineer** [comment]
As a note:
There is now a `getLights2` method which returns all of the light names mapped to their current state. The method to switch the light's state is now called `setLightState`, which I've tested and it seems to be working fine, although, if any issues persist, please notify me.
