### ISSUE TITLE
Crash with MTS V19.13+

### ISSUE THREAD

**Issue by NightScale5755** [SteveTheEngineer/Immersive-Vehicles-Remote-Control#3]
Hello. When I try to place a vehicle-controller block with this mod, and MTS V19.13.0 or above, I get a crash...
[crash-2021-01-24_02.07.26-client.txt](https://github.com/SteveTheEngineer/Immersive-Vehicles-Remote-Control/files/5861752/crash-2021-01-24_02.07.26-client.txt)

**Comment by SteveTheEngineer** [comment]
The version 1.6 of Immersive Vehicles Remote Control works only with MTS version 19.12.0. Please wait until the next release of the mod

**Comment by NightScale5755** [comment]
ok. Sorry to have bothered you then.
