### ISSUE TITLE
Crash with the latest release.

### ISSUE THREAD

**Issue by NightScale5755** [SteveTheEngineer/Immersive-Vehicles-Remote-Control#4]
Hello. Me again...
I'm using IVRC version 1.7
IV version 19.14.0
MTS OCP version 19
As well as OpenComputers version 1.7.5.192

Getting an odd crash related to material types...

[crash-2021-02-09_19.08.35-client.txt](https://github.com/SteveTheEngineer/Immersive-Vehicles-Remote-Control/files/5955232/crash-2021-02-09_19.08.35-client.txt)

**Comment by SteveTheEngineer** [comment]
Fixed in 1.8. Thanks for bringing this to my attention!
