### ISSUE TITLE
Yet more Crash-Happy MC.

### ISSUE THREAD

**Issue by NightScale5755** [SteveTheEngineer/Immersive-Vehicles-Remote-Control#7]
Heya. Just recently got back into Minecraft, and I noticed this mod crashes with any MTS/IV version newer 21.2.0.
Anyways. Look forward to more great updates. I wish you the best!

**Comment by SteveTheEngineer** [comment]
Each IVRC version is tied to a specific MTS version, see the file names on the files page [here](https://www.curseforge.com/minecraft/mc-mods/immersive-vehicles-remote-control/files). 2.7 though is coming with support for the latest MTS version. This is also mostly a duplicate of #3.

**Comment by SteveTheEngineer** [comment]
2.7 has been released. Closed.
